### ISSUE TITLE
Question about non-entity words.

### ISSUE THREAD

**Issue by stvhuang** [DreamInvoker/GAIN#10]
As mentioned in __Section 3.1 Encoding Module__ in the paper, it says "We introduce _None_ entity type and id for those words not belonging to any entity".

However, the proposed model seems to not use any non-entity words.

In __Mention-level Graph Aggregation Module__, the graph only contains entities and not non-entities.

Thus, my question is that __are non-entity words are just dropped from the graph's input or I overlooked some details about the model__.

Thanks!

**Comment by stvhuang** [comment]
Another question.

IMHO, the context may contain some information that can help deciding the relation between entities.

If GAIN does not take non-entity context words into consideration, may I ask what's the reason behind it.

**Comment by DreamInvoker** [comment]
Thank you for your interest in our work!

For the first question:
Yes, we drop all non-entity words in mention-level graph. Because we think that mention nodes and document node initialized with contextualized features implicitly take into account the context words.

For the second question:
Considering the context words explicitly may help GAIN perform better since a relation could be expressed through both context and corresponding entity pair itself.

**Comment by stvhuang** [comment]
Thanks for your answering.
